encoder_training:
  ada_max_p: 0.5
  aug: ada
  ada_interval: 4
  ada_kimg: 250
  batch: 32
  batch_val: 32
  beta_first: 0.0
  beta_sec: 0.99
  blur_enable: true
  cond: false
  cooldown_w: true
  cropping_dataset: center
  data: /home/datasets/gan_encoder_training/cityscapes # path to real data
  data_fake: /home/code_repo/fake_cityscapes_random_50k_res512 # path to GAN generated fake data
  dataset_name: mix_bdd100k # self-defined dataset name
  dlr: 1.0e-05
  dry_run: false
  ema_enable: true
  ema_kimg: 10
  ema_rampup: 0.05
  fpn_feature_dim: 1024
  gamma: 0.1
  generator: stylegan2
  label_dim: 0
  gpus: 1
  img_ratio: '2'
  input_mode: random
  image_snapshot_ticks: 1
  kimg: 12000
  lambda_adv_loss: 0.1
  lambda_e_feat: 0.2
  lambda_infonce: 0.1
  lambda_kl: 0.1
  lambda_lap: 5.0
  lambda_lpips: 10.0
  lambda_mse: 1.0
  lambda_noise: 0.1
  lambda_ssim: 0.01
  lambda_w: 0.1
  loss_mode: hinge
  lr: 0.0001
  lr_decay: 1.0e-05
  lr_decay_iter_end: 250000
  lr_decay_iter_start: 100000
  mask_height_divide: 16
  mask_ratio: 0.25
  mask_size: 4
  masked_lpips_loss: false
  masked_noise_loss: true
  masked_noise_mode: normal
  mirror: true
  new_img_for_d: true
  nobench: false
  noise_predict_from: 128
  noise_predict_until: 128
  num_masked_layer: 2
  optimizer: ranger
  outdir: /home/code_repo/training_outputs_temp # output dir
  pkl_dir: /home/code_repo/pretrained/pretrained_model_stylegan/stylegan2-random-cityscapes-train-z512-res512.pkl # path to pretrained GAN model
  reconstruction_loss: L2
  resolution: 512
  resume: null
  seed: 0
  snap: 4
  save_model_ticks: 1
  style_layers_coarse: 5
  style_layers_fine: 7
  style_layers_medium: 6
  subbatch: 16
  target: 0.12
  tick: 4
  use_same_mask: false
  use_w: true
  val_size: 300
  w_out_dim: 512
  workers: 3
  D_reg_interval: 16 